### ISSUE TITLE
remark-align  v1.1.0  TypeError: Cannot set property 'leftAligned' of undefined

### ISSUE THREAD

**Issue by imcuttle** [zestedesavoir/zmarkdown#200] opened 2018-02-19 05:37 UTC
remark-align  v1.0.x is fine

**Comment by imcuttle** [comment] 2018-02-19 05:52
the version of `remark`: 8.0.0

**Comment by vhf** [comment] 2018-02-19 06:11
Please give a little more details, I need to reproduce this bug in order to fix it.

What Markdown input consistently triggers this exception? Do you have some specific configuration?

**Comment by imcuttle** [comment] 2018-02-19 07:13
```js
remark()
  .use(require('remark-gemoji-to-emoji'))
  .use(require('remark-html'))
  .use(require('remark-slug'))
  .use(require('remark-autolink-headings'))
  .use(require('remark-align'))
  .process('  some markdown ')
```
```text
    "remark": "^8.0.0",
    "remark-align": "~1.0.7",
    "remark-autolink-headings": "^5.0.0",
    "remark-gemoji-to-emoji": "^1.1.0",
    "remark-highlight.js": "^5.0.0",
    "remark-html": "^6.0.1",
    "remark-slug": "^4.2.3",
```

The above code would throw error: `TypeError: Cannot set property 'leftAligned' of undefined`

However, A few days ago, It works fine.

I consider the reason of the bug is here
[remark-align/src/index.js#L113](https://github.com/zestedesavoir/zmarkdown/blob/1102a53fb60e78f8709c6946e0ff1c427372797b/packages/remark-align/src/index.js#L113)
`Compiler.prototype.visitors` is `undefined`.

the old version of `remark-align@1.0.7` is OK.

**Comment by vhf** [comment] 2018-02-19 07:19
Try moving it before `remark-html`, I think this the issue.

**Comment by imcuttle** [comment] 2018-02-19 07:35
It works!

Thanks

**Comment by vhf** [comment] 2018-02-19 09:01
Nice, I'll close this issue then.

Two notes:

* `remark-align` parses new Markdown syntax into new MDAST node types, its compiler is designed to go from MDAST to Markdown again. Since it's a plugin designed to work on Markdown and not on HTML, hence the prefix `remark-` in `remark-align`, that's the reason why you need to run it *before* `remark-html` or any `rehype-` transform. In general, all `remark-` plugins need to run before `remark-html`. I'd suggest you stop using `remark-html` and rely on `remark-rehype` to convert the Markdown AST (MDAST) to the HTML AST (HAST), then run `rehype-stringify` to get the HTML. See the warning message at the beginning of this readme: https://github.com/remarkjs/remark-html
* [Not the friendliest commit message](https://github.com/picidaejs/picidaejs/commit/5a828714c36a3208d5c4906c18b564daec5effab)

**Closed by vhf** 2018-02-19 09:01 UTC
