### ISSUE TITLE
JSFiddle: add direct link as legend

### ISSUE THREAD

**Issue by Vayel** [zestedesavoir/zmarkdown#503] opened 2023-12-29 12:51 UTC
# Problem

Some users can't see the JSFiddle iframes due to browser plugins like AdBlock.

# Proposed solution

As a simple fix, we can add the link to the fiddle as a legend to the iframe.

Currently, the user can't specify any legend for the iframe (contrary to images for instance) so there's no conflict.

**Comment by StaloneLab** [comment] 2023-12-30 10:05
Hello, thanks for the issue, I had never heard of this problem before. Testing with uBlock Origin, JSfiddle frames show as expected. Could you please post here your full configuration (OS, browser, plugins (the original AdBlock?) and custom settings)? I would like to reproduce the problem to see what can be done; if you could also add a screenshot of what you see, that could prove to be helpful.

Regarding the idea of having the link inside the legend, I am not convinced: legends can indeed be used for iframes, see for instance [this tutorial](https://zestedesavoir.com/tutoriels/3790/modeliser-une-epidemie/#la-simulation) (content in French). The following Markdown gives the result you can see:

```md
!(https://jsfiddle.net/outLgfwk/)
Video: Simulation stochastique du processus d'infection-guérison.
```

Maybe you were referring to the alternative text instead of legend (ie. the text in square brackets `![alt text](link)`)? In this case, I do not think there is a way to add this kind of text to an iframe, as these do not support the `alt` attribute.

**Comment by Vayel** [comment] 2023-12-31 10:54
Thanks for the answer @StaloneLab!

I didn't meet the bug but here are examples (French): https://zestedesavoir.com/tutoriels/2238/introduction-aux-systemes-distribues/#p194985

Indeed, we can already add a legend to an iframe (with a non intuitive syntax as it's not a video). But my proposal is to automatically display the JSFiddle link for users who can't see the iframe.

**Comment by StaloneLab** [comment] 2023-12-31 11:45
Yeah fiddles are quite... fiddly? Most of our embed are videos, so we used `Video:` for captioning, although it is therefore not so clear with other types of embeds. Currently, we do not have any way to distinguish between embed types, and it's not that much of a problem to invest time on it.

Back to the subject, I agree with you, I am simply wondering how what you suggest can be done: how should we display the embed link for users who can't see it? I am not aware of any way to do this in HTML.

**Comment by LikaKavkasidze** [comment] 2024-02-11 15:45
Up @Vayel

**Comment by LikaKavkasidze** [comment] 2024-03-28 16:22
Closing since I see nothing to be done. Feel free to reopen if anyone comes with an idea.

**Closed by LikaKavkasidze** 2024-03-28 16:22 UTC
Labels: type/request, semver/minor, status/waiting
