### ISSUE TITLE
rebber : striked out text in titles

### ISSUE THREAD

**Issue by Karnaj** [zestedesavoir/zmarkdown#308] opened 2018-12-30 15:22 UTC
Striked-out text leads to a LaTeX error, `\texorpdfstring` should be used. Then

```
# Title ~~word~~
```

should give

```latex
\titleCommand{\texorpdfstring{Title \sout{word}}{Title word}}
```

**Comment by artragis** [comment] 2018-12-30 16:20
nota "titleCommand" means "addPart" or "addChapter" etc. am i right @Karnaj ?

**Comment by Karnaj** [comment] 2018-12-30 17:04
`\titleCommand` could be `\levelOneTitle` , `\levelTwoTtitle`, etc.

**Comment by Karnaj** [comment] 2018-12-31 20:01
We can decide to always use `\texorpdfstring`, even when there is no striked-out text.

**Comment by vhf** [comment] 2019-01-01 17:02
I don't understand the issue, please give more context. When does this happen? How can this be fixed? Why are you using a title in your example?

**Comment by Karnaj** [comment] 2019-01-02 19:07
The fact is that there is a conflit with `sout` and `hyperref` when `sout` is used in a title command. And `zmarkdown` transforms `# Two ~~words~~` into the following LaTeX code.

```latex
\levelOneTitle{Title \sout{word}}
```

Because of the conflict, it cannot be compiled.  It happens for instance [in this tutorial](https://zestedesavoir.com/tutoriels/686/arduino-premiers-pas-en-informatique-embarquee/742_decouverte-de-larduino/3415_quelques-bases-elementaires/#les-bases-du-de-comptage) with the title `Les bases du ~~de~~ comptage`.

**Comment by pierre-24** [comment] 2019-01-03 12:45
To add some context, when @Karnaj refers to `hyperref`, he refers to the package that allow links (like titles in the table of content, but also hyperlinks) to be clickable. Here, the issue is that this package also try to create a table of content for the PDF file (not to be confused from the one that is printed in the beginning, what you usually get in a side pane of your PDF viewer), which does not (seems to) accept a lot of formatting. 

The `\texorpdfstring{a}{b}` command allow to separate what the title should looks like on the page (with full formatting,  first argument `a`) from what should be into the pdf table of content (without any formatting [even though italic or bold seems ok], second argment `b`). 

I would like to try first a little trick I found on StackOverflow (see https://github.com/zestedesavoir/latex-template/issues/102), but if not, that's something you'll need to do on your side :) (because LaTeX is stupid for that).

**Comment by pierre-24** [comment] 2019-01-04 19:34
Ok, **you can close this issue**, I found a way to fix it in the template directly. That may happen with other elements, though (I checked the common ones), but now we know how to handle it.

**Closed** 2019-01-05 13:17 UTC
